version: "3"
services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        network_mode: bridge
        restart: always
    redisinsight:
        image: redislabs/redisinsight:latest
        container_name: redisinsight
        ports:
            - "8001:8001"
        network_mode: bridge
        restart: always
        volumes:
            - redis-db:/db
        depends_on:
            - redis

volumes:
  redis-db:
    external: true