services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - redis_network
    restart: no

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540
    networks:
      - redis_network
    volumes:
      - redis-db:/db
    depends_on:
      - redis
    restart: no

networks:
  redis_network:
    driver: bridge

volumes:
  redis-db:
    external: true
