services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: bridge
    restart: no
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@totvs.com.br"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "15432:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres
  #   network_mode: bridge
  #   restart: always

volumes:
  postgres-data:
    external: true
  # pgadmin-data:
  #   external: true