version: "3"

services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      environment:
          SA_PASSWORD: "Totvs@123"
          ACCEPT_EULA: "Y"
          MSSQL_AGENT_ENABLED: "true"
      ports:
          - "1433:1433"
      volumes:
        - mssql-data:/var/opt/mssql
      network_mode: bridge
      restart: always

volumes:
  mssql-data:
    external: true