version: "3"
services:
    seq:
        image: datalust/seq
        container_name: seq
        environment:
          ACCEPT_EULA: "Y"
        ports:
            - "45341:80"
            - "5341:5341"
        volumes:
            - seq-data:/var/opt/seq
        network_mode: bridge
        restart: always

volumes:
  seq-data:
    external: true