services:
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: mysqlDB
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    network_mode: bridge
    restart: no

volumes:
  mysql-data:
    external: true
